name: advanced_routing_flutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get:
    git:
      url: https://github.com/jonataslaw/getx
  url_strategy: ^0.2.0
  shared_preferences: ^2.1.0
  fluttertoast: ^8.2.1
  firebase_dynamic_links: ^5.1.1
  firebase_core: ^2.10.0
#  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  #    - assets/launcher/

  fonts:
    - family: Asap
      fonts:
        - asset: assets/fonts/Asap-Light.ttf
          weight: 300
        - asset: assets/fonts/Asap-Regular.ttf
          weight: 400
        - asset: assets/fonts/Asap-Medium.ttf
          weight: 500
        - asset: assets/fonts/Asap-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Asap-Bold.ttf
          weight: 700
