// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVpoFhVg5tGXOVMyB9oeAQTxBbR_kEa0o',
    appId: '1:788316081318:web:97cd5528a99ff604e53867',
    messagingSenderId: '788316081318',
    projectId: 'flutter-chat-f6130',
    authDomain: 'flutter-chat-f6130.firebaseapp.com',
    databaseURL: 'https://flutter-chat-f6130.firebaseio.com',
    storageBucket: 'flutter-chat-f6130.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyyu4Tt4-pWbJm4YLERnb-zBjI-w5nWy0',
    appId: '1:788316081318:android:0af2676b9d9a9b04e53867',
    messagingSenderId: '788316081318',
    projectId: 'flutter-chat-f6130',
    databaseURL: 'https://flutter-chat-f6130.firebaseio.com',
    storageBucket: 'flutter-chat-f6130.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVEjmB-VPq-14ayad41U5koAyRw1t7hhM',
    appId: '1:788316081318:ios:c9c22c26034ff135e53867',
    messagingSenderId: '788316081318',
    projectId: 'flutter-chat-f6130',
    databaseURL: 'https://flutter-chat-f6130.firebaseio.com',
    storageBucket: 'flutter-chat-f6130.appspot.com',
    androidClientId: '788316081318-23nf06dtqvn2t0137mi5t8og7au1mkun.apps.googleusercontent.com',
    iosClientId: '788316081318-s1h52ei031sc4e0f8ijpu4utlvs52439.apps.googleusercontent.com',
    iosBundleId: 'com.kumarsunil.advancedRoutingFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVEjmB-VPq-14ayad41U5koAyRw1t7hhM',
    appId: '1:788316081318:ios:c9c22c26034ff135e53867',
    messagingSenderId: '788316081318',
    projectId: 'flutter-chat-f6130',
    databaseURL: 'https://flutter-chat-f6130.firebaseio.com',
    storageBucket: 'flutter-chat-f6130.appspot.com',
    androidClientId: '788316081318-23nf06dtqvn2t0137mi5t8og7au1mkun.apps.googleusercontent.com',
    iosClientId: '788316081318-s1h52ei031sc4e0f8ijpu4utlvs52439.apps.googleusercontent.com',
    iosBundleId: 'com.kumarsunil.advancedRoutingFlutter',
  );
}
